project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "Sports Performance"
  author:
    - Aadarsh Agarwal (aa5521)
    - Annette Antony (aa5522)
    - Mehyar Sharma (ms7070)
  repo-url: https://github.com/annette-antony/sportsperformance
  date: 11/19/2024
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: flatly
    code-fold: true


